"""
readers/coda.py
===============
Reader for CODA CFD solver output.

Expected directory layout
--------------------------
::

    root_dir/
    ├── metadata/
    │   └── cases_metadata.json          ← generated by GANDALF
    └── outputs/
        ├── aoa_3.00_mach_0.750/
        │   ├── output_0_surface.vtu
        │   ├── output_0__monitors_*.dat
        │   └── ...
        └── aoa_5.00_mach_0.750/
            └── ...

If ``cases_metadata.json`` is missing, the reader attempts to infer the
folder format automatically from the folder names in ``outputs/``.

Case identity vs. execution state
----------------------------------
Two DataFrames describe the case space and must not be confused with
each other:

* ``self.metadata['df_cases']`` — the **identity / definition** of every
  case (design-variable values, ``case_idx``, and, once created, subset
  membership).  It is loaded once from ``cases_metadata.json`` (or
  inferred from folder names) and is the *source of truth* for "which
  cases exist and what are they".  It is mutated in place (e.g. the
  ``'folder'`` and ``'subsets'`` columns are filled in), but never
  replaced wholesale, so external references to it (and anything derived
  from it, such as subset membership) stay valid across re-parses.
* ``self.df_state`` — a **derived, disposable view** of the current
  execution state (how many stages have completed for each case). It is
  fully rebuilt every time ``parse_simulation_dirs()`` runs, by joining
  the on-disk state discovered under ``outputs/`` with
  ``metadata['df_cases']``. It must never be treated as an independent
  source of case identity: if ``df_state`` and ``df_cases`` were to
  disagree, ``df_cases`` wins.

Case subsets
------------
A *subset* is a named grouping of case identities (``df_cases`` rows).
Subsets are the recommended way to repeatedly select the same group of
cases (e.g. "every case at Mach 0.7") across ``extract_inputs``,
``extract_outputs`` and the residuals helpers, instead of re-typing the
same ``cases_idx`` list everywhere. See :meth:`CODAReader.define_subset`
for the full API.
"""

import os
import re
import json
import warnings
import time
from collections import defaultdict
from typing import Literal, Union

import numpy as np
import pandas as pd
import pyvista as pv
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.colors import BoundaryNorm

from ..sam import SAM
from .base import BaseReader


class CODAReader(BaseReader):
    """
    Reader for CODA CFD solver output (.vtu surface / volume files).

    Parameters
    ----------
    root_dir : str
        Path to the dataset root directory (passed by FRODO).

    Attributes set after ``parse_simulation_dirs``
    -----------------------------------------------
    metadata : dict
        Keys: 'eq_type', 'folder_fmt', 'design_vars', 'num_stages',
        'df_cases'. ``metadata['df_cases']`` is the case-identity table
        (see module docstring); it additionally carries a ``'subsets'``
        column once :meth:`define_subset` has been used.
    sim_metadata : dict
        Keyed by folder name.  Each value contains path, stage dict and
        design-variable values.
    df_state : pd.DataFrame
        Derived execution-state view, one row per simulation. Columns:
        design vars + 'stage' + everything merged in from
        ``metadata['df_cases']`` (including ``'case_idx'``, ``'folder'``
        and, once defined, ``'subsets'``).
    subsets : dict[str, list[int]]
        Named groupings of case positions (``df_cases`` row positions).
        Populated by :meth:`define_subset`. Empty dict until the first
        subset is defined.
    active_cases_idx : dict[str, list[int]]
        For every CADGroup key already populated via ``extract_inputs``,
        the exact (global, ``df_cases``-relative) case positions that
        were extracted into it, in the order used to build ``data_dict``.
        This mirrors the bookkeeping already performed by
        ``NUMPYReader._active_cases_idx`` and exists so that later code
        (e.g. a future Sets/Stats method) can map the *local* case axis
        of an already-extracted CADGroup back to global ``df_cases``
        positions/subsets without re-deriving it. Empty dict until the
        first call to ``extract_inputs``.
    """

    def __init__(self, root_dir: str, **kwargs):
        super().__init__(root_dir, **kwargs)
        self.output_dir = os.path.join(self.root_dir, "outputs")
        print(f'\n NEW CODA SIMULATION WILL BE LOADED FROM {root_dir}')

        # ── Case subsets & extraction bookkeeping ──────────────────────────
        # 'subsets' is the single source of truth for named case groupings
        # (see define_subset / _resolve_cases_idx). 'active_cases_idx' is
        # populated by extract_inputs and records, per CADGroup key, which
        # global case positions were extracted.
        self.subsets: dict          = {}
        self.active_cases_idx: dict = {}

        try:
            meta_path = os.path.join(root_dir, 'metadata', 'cases_metadata.json')
            with open(meta_path, 'r') as fh:
                cm = json.load(fh)

            self.metadata = {
                'eq_type':     cm.get('eq_type',    None),
                'folder_fmt':  cm.get('folder_fmt', None),
                'design_vars': cm.get('design_vars', None),
                'num_stages':  cm.get('num_stages', None),
            }

            df_cases = (
                pd.DataFrame.from_dict(cm.get('df_cases', {}))
                .sort_values(by=self.metadata['design_vars'][0],
                             ignore_index=True, axis=0)
                .reset_index(drop=True)
            )
            if "case_idx" not in df_cases.columns:
                df_cases.insert(0, "case_idx", df_cases.index.astype(np.int32))
            self.metadata['df_cases'] = df_cases

        except Exception as exc:
            print(
                "WARNING: cases_metadata.json not found or could not be "
                "loaded. Folder format will be inferred from folder names.\n"
            )
            print(exc)
            self._infer_metadata_from_folders()

        self._sync_subsets_column()

    # ── Metadata inference fallback ───────────────────────────────────────────

    def _infer_metadata_from_folders(self):
        """Infer metadata from output folder names when JSON is missing."""
        folders       = os.listdir(self.output_dir)
        possible_sep  = ['_', '-']
        sep_list, params_list, nfiles_list = [], [], []

        for folder in folders:
            for sep in possible_sep:
                if sep in folder:
                    parts = folder.split(sep)
                    params = [
                        float(re.findall(r"-?\d+\.?\d*", p)[0])
                        for p in parts
                        if re.findall(r"-?\d+\.?\d*", p)
                    ]
                    params_list.append(params)
                    sep_list.append(sep)
                    nfiles_list.append(len(
                        SAM.Backpack.pattern_pocket.find_files(
                            os.path.join(self.output_dir, folder),
                            file_end='.h5', not_contains='ci',
                        )
                    ))

        if not params_list:
            raise ValueError(
                "No simulation folders found or no numeric parameters "
                "detected in folder names."
            )

        if not (
            all(len(p) == len(params_list[0]) for p in params_list)
            and all(s == sep_list[0] for s in sep_list)
            and all(n == nfiles_list[0] for n in nfiles_list)
        ):
            raise ValueError(
                "Inconsistent folder naming. "
                "Please provide a valid cases_metadata.json file."
            )

        parts = folders[0].split(sep_list[0])
        self.metadata = {
            'eq_type': None,
            'folder_fmt': sep_list[0].join([
                p if not re.findall(r"-?\d+\.?\d*", p) else "{}"
                for p in parts
            ]),
            'design_vars': [parts[i] for i in range(0, len(parts), 2)],
            'num_stages':  nfiles_list[0],
        }

        df_arr = np.zeros((len(folders), len(params_list[0])), dtype=float)
        for f_idx, folder in enumerate(folders):
            df_arr[f_idx, :] = params_list[f_idx]

        df_cases = pd.DataFrame(
            df_arr, columns=self.metadata['design_vars']
        ).reset_index(drop=True)
        df_cases.insert(0, "case_idx", df_cases.index.astype(np.int32))
        self.metadata['df_cases'] = df_cases

    # ── Case subsets ───────────────────────────────────────────────────────────

    def define_subset(
        self,
        name: str,
        cases_idx: Union[list, tuple, int, str],
        overwrite: bool = False,
    ) -> list:
        """
        Define (or redefine) a named subset of cases from
        ``metadata['df_cases']``.

        A subset is simply a stored, named list of ``df_cases`` row
        positions.  Once defined, it can be referenced by name from
        :meth:`extract_inputs`, :meth:`extract_outputs` and the CODA
        residuals helpers that accept a ``subset`` argument, instead of
        repeating the same ``cases_idx`` selection everywhere.

        Case selection reuses the exact same normalisation logic already
        used by ``cases_idx`` elsewhere in the reader
        (``BaseReader._normalise_cases_idx``), so every value accepted by
        ``extract_inputs(cases_idx=...)`` today (``'all'``, an ``int``, a
        ``range``, or a ``list``/``tuple`` of ints) is also accepted here.

        A case may belong to any number of subsets simultaneously: the
        canonical storage is ``self.subsets``, a plain
        ``dict[str, list[int]]`` (not a single-valued column), which
        removes the "one case, one label" limitation a boolean/categorical
        column would impose. For inspection convenience this is mirrored,
        read-only, onto a ``'subsets'`` column of ``metadata['df_cases']``
        (one list of subset names per row) every time subsets change —
        but that column is never read back to resolve a subset; it exists
        purely so a human (or ``df_cases.head()``) can see membership at a
        glance.

        Parameters
        ----------
        name : str
            Subset name.  Must be a non-empty string (surrounding
            whitespace is stripped).  Must not already exist unless
            ``overwrite=True``.
        cases_idx : 'all', int, range, list[int] or tuple[int]
            Case selection, normalised via
            ``BaseReader._normalise_cases_idx`` against
            ``metadata['df_cases']``.
        overwrite : bool
            If True, silently replaces an existing subset with the same
            name. If False (default) and the name already exists, raises
            ``ValueError``.

        Returns
        -------
        list[int]
            The resolved, sorted list of case positions now stored under
            ``self.subsets[name]``.

        Raises
        ------
        ValueError
            If ``name`` is empty/whitespace-only, if it already exists and
            ``overwrite=False``, if ``cases_idx`` has an unsupported type
            or string value, or if the resolved selection is empty.
        IndexError
            If ``cases_idx`` contains out-of-range positions.
        RuntimeError
            If ``metadata['df_cases']`` is not available.

        Examples
        --------
        Define a subset from an explicit list of case positions::

            db.define_subset(name='mach_07', cases_idx=[0, 1, 2])

        Define a subset covering every case (rarely useful on its own,
        but handy as a documented alias)::

            db.define_subset(name='every_case', cases_idx='all')

        Redefine an existing subset after discovering more cases at that
        Mach number::

            db.define_subset(
                name='mach_07', cases_idx=[0, 1, 2, 9], overwrite=True,
            )

        A case can belong to more than one subset::

            db.define_subset(name='mach_07', cases_idx=[0, 1, 2])
            db.define_subset(name='low_aoa', cases_idx=[0, 3])
            print(db.list_subsets())
            # {'mach_07': [0, 1, 2], 'low_aoa': [0, 3]}
        """
        if not isinstance(name, str) or not name.strip():
            raise ValueError("'name' must be a non-empty string.")
        name = name.strip()

        if name in self.subsets and not overwrite:
            raise ValueError(
                f"Subset '{name}' already exists. "
                "Pass overwrite=True to redefine it."
            )

        df_cases = self.metadata.get('df_cases')
        if df_cases is None or df_cases.empty:
            raise RuntimeError(
                "'df_cases' is not available; cannot define a subset."
            )

        resolved = self._normalise_cases_idx(cases_idx, df_cases)
        if not resolved:
            raise ValueError(
                f"Subset '{name}' would be empty; refusing to define it."
            )

        self.subsets[name] = sorted(set(int(i) for i in resolved))
        self._sync_subsets_column()

        return list(self.subsets[name])

    def get_subset(self, name: str) -> list:
        """
        Return the list of case positions belonging to a named subset.

        Parameters
        ----------
        name : str
            Subset name, as passed to :meth:`define_subset`.

        Returns
        -------
        list[int]
            Copy of the stored case-position list; safe to mutate.

        Raises
        ------
        KeyError
            If ``name`` is not a defined subset.

        Examples
        --------
        ::

            db.define_subset(name='mach_07', cases_idx=[0, 1, 2])
            print(db.get_subset('mach_07'))   # [0, 1, 2]
        """
        if name not in self.subsets:
            raise KeyError(
                f"Subset '{name}' not found. "
                f"Available subsets: {list(self.subsets)}."
            )
        return list(self.subsets[name])

    def list_subsets(self) -> dict:
        """
        Return every currently defined subset.

        Returns
        -------
        dict[str, list[int]]
            Copy of ``self.subsets`` (both the dict and every contained
            list are copies; safe to mutate).

        Examples
        --------
        ::

            db.define_subset(name='mach_07', cases_idx=[0, 1, 2])
            db.define_subset(name='mach_08', cases_idx=[3, 4, 5])
            print(db.list_subsets())
            # {'mach_07': [0, 1, 2], 'mach_08': [3, 4, 5]}
        """
        return {k: list(v) for k, v in self.subsets.items()}

    def remove_subset(self, name: str) -> None:
        """
        Delete a previously defined subset.

        Parameters
        ----------
        name : str
            Subset name to remove.

        Raises
        ------
        KeyError
            If ``name`` is not a defined subset.

        Side-effects
        ------------
        Refreshes the ``'subsets'`` mirror column on
        ``metadata['df_cases']``.

        Examples
        --------
        ::

            db.remove_subset('mach_07')
        """
        if name not in self.subsets:
            raise KeyError(
                f"Subset '{name}' not found. "
                f"Available subsets: {list(self.subsets)}."
            )
        del self.subsets[name]
        self._sync_subsets_column()

    def _sync_subsets_column(self) -> None:
        """
        Refresh the read-only ``'subsets'`` mirror column on
        ``metadata['df_cases']`` from ``self.subsets`` (the canonical
        source of truth).

        Called automatically after every subset mutation
        (``define_subset`` / ``remove_subset``). Never reads the column
        back — it exists purely for human inspection (e.g.
        ``db.metadata['df_cases'][['case_idx', 'subsets']]``).

        Examples
        --------
        Not normally called directly; exposed mainly for completeness and
        testing::

            db.subsets['mach_07'] = [0, 1, 2]
            db._sync_subsets_column()
            print(db.metadata['df_cases']['subsets'].tolist())
        """
        df_cases = self.metadata.get('df_cases')
        if df_cases is None:
            return

        membership = {pos: [] for pos in range(len(df_cases))}
        for subset_name, positions in self.subsets.items():
            for pos in positions:
                if pos in membership:
                    membership[pos].append(subset_name)

        df_cases['subsets'] = [
            membership[pos] for pos in range(len(df_cases))
        ]

    def _resolve_cases_idx(
        self,
        cases_idx: Union[list, tuple, int, str] = 'all',
        subset: Union[str, None] = None,
    ) -> list:
        """
        Central case-selection resolver shared by every CODA method that
        accepts both a ``cases_idx`` and a ``subset`` argument.

        Semantics
        ---------
        * ``subset is None`` → behaves exactly like
          ``BaseReader._normalise_cases_idx(cases_idx, df_cases)``: the
          pre-existing ``cases_idx``-based selection, unchanged.
        * ``subset`` is a valid subset name **and** ``cases_idx`` is left
          at its default value (``'all'``) → the subset's case positions
          are used, and ``cases_idx`` is silently ignored (it was never
          set to anything meaningful by the caller).
        * ``subset`` is a valid subset name **and** ``cases_idx`` was
          explicitly set to something other than ``'all'`` → this is an
          unresolvable ambiguity (the caller asked for two different
          selections at once) and a ``ValueError`` is raised rather than
          silently picking one.

        This makes the "subset wins, cases_idx is ignored" rule from the
        module/class docs unambiguous: a default ``cases_idx='all'`` is
        always compatible with any subset (there is nothing to conflict
        with), while a real, non-default ``cases_idx`` together with a
        ``subset`` is rejected outright instead of guessing which one the
        caller meant.

        Parameters
        ----------
        cases_idx : 'all', int, range, list[int] or tuple[int]
            Same accepted values as ``BaseReader._normalise_cases_idx``.
            Default ``'all'``.
        subset : str or None
            Name of a previously defined subset (see
            :meth:`define_subset`). Default None.

        Returns
        -------
        list[int]
            Resolved, validated list of case positions.

        Raises
        ------
        KeyError
            If ``subset`` is given but not a defined subset name.
        ValueError
            If both ``subset`` and a non-default ``cases_idx`` are given,
            or if ``cases_idx`` itself is invalid (propagated from
            ``BaseReader._normalise_cases_idx``).
        IndexError
            Propagated from ``BaseReader._normalise_cases_idx`` when
            ``cases_idx`` contains out-of-range positions.

        Examples
        --------
        Default behaviour, unchanged from before subsets existed::

            idx = reader._resolve_cases_idx(cases_idx=[0, 1, 2])
            idx = reader._resolve_cases_idx(cases_idx='all')

        Selecting via a subset::

            reader.define_subset(name='mach_07', cases_idx=[0, 1, 2])
            idx = reader._resolve_cases_idx(subset='mach_07')
            # idx == [0, 1, 2]; cases_idx defaulted to 'all', so no conflict.

        Conflicting selection — raises ``ValueError``::

            reader._resolve_cases_idx(cases_idx=[5, 6], subset='mach_07')
        """
        if subset is not None:
            if subset not in self.subsets:
                raise KeyError(
                    f"Subset '{subset}' not found. "
                    f"Available subsets: {list(self.subsets)}."
                )
            is_default = isinstance(cases_idx, str) and cases_idx.lower() == 'all'
            if not is_default:
                raise ValueError(
                    "Both 'subset' and an explicit 'cases_idx' were "
                    "provided; this selection is ambiguous. Either omit "
                    "'cases_idx' (or leave it as 'all') when using "
                    "'subset', or omit 'subset' and select cases via "
                    "'cases_idx' as before."
                )
            return list(self.subsets[subset])

        df_cases = self.metadata.get('df_cases', pd.DataFrame())
        return self._normalise_cases_idx(cases_idx, df_cases)

    # ── BaseReader interface ──────────────────────────────────────────────────

    def parse_simulation_dirs(self) -> None:
        """
        Walk ``outputs/`` and build ``sim_metadata`` and ``df_state``.

        Matches folder names against the format pattern, maps each folder
        to the closest entry in ``df_cases`` (by Euclidean distance in the
        design-variable space), and counts available stages.

        ``df_state`` is fully rebuilt on every call by merging the
        freshly-scanned execution state with ``metadata['df_cases']`` — it
        is a derived view, never an independent source of case identity.
        ``metadata['df_cases']`` itself (and therefore any subset defined
        via :meth:`define_subset`) is only mutated in place (e.g. the
        ``'folder'`` column is filled in) and survives repeated calls to
        this method unchanged in row count/order.

        Populates
        ---------
        self.sim_metadata : dict
            Keyed by folder name. Values: path, stages dict, design-var
            values, computation_times list.
        self.df_state : pd.DataFrame
            One row per matched simulation.
        """
        pattern = SAM.Backpack.pattern_pocket.FilenamePattern.from_template(
            self.metadata["folder_fmt"], numeric=True
        ).compiled

        for folder in os.listdir(self.output_dir):
            if not pattern.match(folder):
                continue

            nums_folder = np.array(
                [float(x) for x in re.compile(r"[-\d\.]+").findall(folder)],
                dtype=float,
            )
            nums_df = self.metadata['df_cases'][
                self.metadata['design_vars']
            ].values
            idx_closest = np.argmin(
                np.linalg.norm(nums_df - nums_folder, axis=1)
            )
            nums = (
                self.metadata['df_cases']
                .iloc[idx_closest][self.metadata['design_vars']]
                .values.tolist()
            )
            self.metadata['df_cases'].at[idx_closest, 'folder'] = folder

            full_path = os.path.join(self.output_dir, folder)
            if not os.path.isdir(full_path):
                continue

            stage_dict: dict = {}
            for fname in os.listdir(full_path):
                if fname.startswith("output_"):
                    parts = fname.split("_")
                    if len(parts) >= 2:
                        stage_raw = os.path.splitext(parts[1])[0]
                        if stage_raw.isdigit():
                            stage = int(stage_raw)
                            ext   = os.path.splitext(fname)[-1].lstrip(".")
                            stage_dict.setdefault(
                                stage, {"files": [], "types": set()}
                            )
                            stage_dict[stage]["files"].append(fname)
                            stage_dict[stage]["types"].add(ext)

            for stage in stage_dict:
                stage_dict[stage]["types"] = list(stage_dict[stage]["types"])

            self.sim_metadata[folder] = {
                "folder":            folder,
                "path":              full_path,
                "stages":            stage_dict,
                "computation times": [],
            }
            self.sim_metadata[folder].update(
                {var: val for var, val in
                 zip(self.metadata["design_vars"], nums)}
            )

        print(f"{len(self.sim_metadata)} simulations found.")

        n_dv = len(self.metadata['design_vars'])
        state_array = np.zeros(
            (len(self.sim_metadata), n_dv + 1), dtype=float
        )
        for n_sim, sim_key in enumerate(self.sim_metadata):
            sim = self.sim_metadata[sim_key]
            for i, var in enumerate(self.metadata['design_vars']):
                state_array[n_sim, i] = sim[var]
            state_array[n_sim, -1] = len(sim["stages"])

        df_state = (
            pd.DataFrame(
                state_array,
                columns=self.metadata['design_vars'] + ['stage'],
            )
            .sort_values(by=self.metadata['design_vars'][0])
            .reset_index(drop=True)
        )
        self.df_state = pd.merge(
            df_state, self.metadata['df_cases'],
            on=self.metadata['design_vars'], how='left',
        )

    def extract_inputs(
        self,
        id_groups: Union[int, tuple],
        vtu_type: Literal['volume', 'surface'] = 'surface',
        method_to_sort: Literal[
            'lexsort', 'centroid', 'kdtree', 'convex_hull'
        ] = 'lexsort',
        cases_idx: Union[list, tuple, int, str] = 'all',
        subset: Union[str, None] = None,
        verbose: bool = False,
    ) -> None:
        """
        Extract input mesh and metadata for one or multiple CADGroup IDs.

        Parameters
        ----------
        id_groups : int or tuple
            Group IDs to process. A tuple of ints merges those groups into
            a single CADGroup key.
            Examples: ``(3,)`` for group 3 alone;
            ``((1, 2), 3)`` to merge groups 1+2 and also process group 3.
        vtu_type : str
            Type of .vtu file to load. Default 'surface'.
        method_to_sort : str
            Cell-centroid sorting method.
            Options: 'lexsort', 'centroid', 'kdtree', 'convex_hull'.
        cases_idx : list, tuple, int or 'all'
            Subset of cases (by df_cases row index) to process. Default
            'all'. Ignored (and must be left at its default) when
            ``subset`` is given — see ``subset`` below.
        subset : str or None
            Name of a subset previously defined via :meth:`define_subset`.
            When given, the cases to process are taken **exclusively**
            from that subset and ``cases_idx`` must be left at its
            default value ``'all'`` (passing both a real ``cases_idx``
            and a ``subset`` raises ``ValueError`` — see
            :meth:`_resolve_cases_idx`). Default None (use ``cases_idx``
            as before).
        verbose : bool
            Print per-case progress.

        Populates
        ---------
        self.data_dict[key] with:
        'Coord', 'NodeCoord', 'FlCc', 'Conec',
        'idx_sort', 'idx_sort_nodes', 'eltype', 'cellOrder', 'pointOrder'.

        Side-effects
        ------------
        Records the resolved, global (``df_cases``-relative) case
        positions used to build each CADGroup in
        ``self.active_cases_idx[key]``.

        Raises
        ------
        KeyError
            If ``subset`` is given but not a defined subset name.
        ValueError
            If both ``subset`` and a non-default ``cases_idx`` are given.
        IndexError
            If ``cases_idx`` contains out-of-range positions.

        Examples
        --------
        Unchanged, cases_idx-based usage::

            db.extract_inputs(id_groups=(3,), cases_idx=[0, 1, 2])
            db.extract_inputs(id_groups=(3,))   # cases_idx defaults to 'all'

        Subset-based usage::

            db.define_subset(name='mach_07', cases_idx=[0, 1, 2])
            db.extract_inputs(id_groups=(3,), subset='mach_07')
        """
        num_stages  = self.metadata.get("num_stages", 1)
        design_vars = self.metadata.get("design_vars", [])
        df_cases    = self.metadata.get("df_cases", pd.DataFrame())

        cases_idx = self._resolve_cases_idx(cases_idx, subset)
        sim_keys  = df_cases.loc[cases_idx, "folder"].tolist()
        ncases    = len(sim_keys)

        sort_fn_map = {
            'lexsort':     SAM.Weapons.sort_lexsort,
            None:          SAM.Weapons.sort_lexsort,
            'centroid':    SAM.Weapons.sort_by_centroid,
            'kdtree':      SAM.Weapons.sort_closed_curve_by_kdtree,
            'convex_hull': SAM.Weapons.sort_points_by_hull_projection,
        }
        if method_to_sort not in sort_fn_map:
            raise ValueError(
                f"method_to_sort '{method_to_sort}' not supported. "
                f"Options: {list(sort_fn_map)}."
            )
        sort_fn = sort_fn_map[method_to_sort]

        for group_id in id_groups:
            ids_to_combine, key_suffix = self._parse_group_id(group_id)
            key = f"CADGroup_{key_suffix}"

            Coord_base = NodeCoord_base = None
            Conec_base = eltype_base = cellOrder_base = pointOrder_base = None
            FlCc = idx_sort = idx_sort_nodes = None

            for stage in range(num_stages):
                if verbose:
                    print(f'Stage {stage}:')
                for cont, case_i in enumerate(cases_idx):
                    sim_key = sim_keys[cont]
                    if verbose:
                        print(f'\t cont={cont}  case={case_i}  folder={sim_key}')
                    try:
                        mesh = self.load_vtu_from_stage(sim_key, stage, vtu_type)

                        if "CADGroupID" not in mesh.cell_data:
                            raise ValueError(
                                "'CADGroupID' not found in mesh cell_data."
                            )

                        mask      = np.isin(mesh.cell_data["CADGroupID"],
                                            ids_to_combine)
                        celdas    = mesh.extract_cells(mask)
                        centroids = np.array(
                            celdas.cell_centers().points, dtype=np.float64
                        )
                        nodes        = np.array(celdas.points, dtype=np.float64)
                        connectivity = (
                            SAM.Backpack.get_unified_connectivity(mesh)[mask]
                        )

                        centroids_sorted, idx       = sort_fn(points=centroids)
                        nodes_sorted,     idx_nodes = sort_fn(points=nodes)

                        if stage == 0 and cont == 0:
                            npoints = centroids.shape[0]
                            nnodes  = nodes.shape[0]

                            idx_sort = np.zeros(
                                (num_stages, ncases, npoints), dtype=np.int32
                            )
                            idx_sort_nodes = np.zeros(
                                (num_stages, ncases, nnodes), dtype=np.int32
                            )
                            FlCc          = np.zeros(
                                (ncases, len(design_vars)), dtype=np.float64
                            )
                            Coord_base     = centroids_sorted.copy()
                            NodeCoord_base = nodes_sorted.copy()
                            Conec_base     = connectivity.copy()
                            eltype_base    = celdas.celltypes.copy()
                            cellOrder_base = np.arange(
                                celdas.n_cells, dtype=np.float64
                            )
                            pointOrder_base = np.arange(
                                celdas.n_points, dtype=np.float64
                            )
                        else:
                            for base, current, label in [
                                (Coord_base,     centroids_sorted, "cell"),
                                (NodeCoord_base, nodes_sorted,     "node"),
                            ]:
                                if not SAM.Backpack.same_columns(
                                    np.stack([base, current], axis=0)
                                ):
                                    raise ValueError(
                                        f"Inconsistent {label} coordinates "
                                        f"at stage {stage}, case {sim_key}."
                                    )

                        idx_sort[stage, cont]       = idx
                        idx_sort_nodes[stage, cont] = idx_nodes
                        if stage == 0:
                            FlCc[cont] = [
                                self.sim_metadata[sim_key][p]
                                for p in design_vars
                            ]

                    except Exception as exc:
                        print(
                            f"Error reading inputs for '{sim_key}', "
                            f"group {group_id}, stage {stage}: {exc}"
                        )

            self.data_dict.setdefault(key, {}).update({
                'Coord':          Coord_base,
                'NodeCoord':      NodeCoord_base,
                'FlCc':           FlCc,
                'Conec':          Conec_base,
                'idx_sort':       idx_sort,
                'idx_sort_nodes': idx_sort_nodes,
                'eltype':         eltype_base,
                'cellOrder':      cellOrder_base,
                'pointOrder':     pointOrder_base,
            })

            self.active_cases_idx[key] = list(cases_idx)

    def extract_outputs(
        self,
        stage: int,
        id_groups: Union[int, tuple],
        vtu_type: Literal['volume', 'surface'] = 'surface',
        cases_idx: Union[list, tuple, int, str] = 'all',
        subset: Union[str, None] = None,
        var_name_excluded: Union[list, tuple, None] = None,
        verbose: bool = False,
    ) -> None:
        """
        Extract cell-based output variables for one or multiple CADGroup IDs.

        Requires ``extract_inputs`` to have been called first (uses
        ``idx_sort`` stored by that method).

        Parameters
        ----------
        stage : int
            Stage number to extract variables from.
        id_groups : int or tuple
            Same format as in ``extract_inputs``.
        vtu_type : str
            Type of .vtu file. Default 'surface'.
        cases_idx : list, tuple, int or 'all'
            Subset of cases. Default 'all'. Ignored (and must be left at
            its default) when ``subset`` is given.
        subset : str or None
            Name of a subset previously defined via :meth:`define_subset`.
            Same semantics as in :meth:`extract_inputs`. **Must match**
            whatever selection (``cases_idx`` or ``subset``) was used in
            the matching ``extract_inputs`` call for the same
            ``id_groups``, since this method reuses the ``idx_sort``
            array built there and indexes it positionally by case order.
            Default None.
        var_name_excluded : list, tuple or None
            Variable names to skip during extraction.
        verbose : bool
            Print per-case progress.

        Populates
        ---------
        self.data_dict[key]['Vars'][str(stage)] with arrays of shape
        (n_points, n_cases) for each scalar variable.

        Raises
        ------
        KeyError
            If ``subset`` is given but not a defined subset name.
        ValueError
            If both ``subset`` and a non-default ``cases_idx`` are given.
        IndexError
            If ``cases_idx`` contains out-of-range positions.
        RuntimeError
            If ``extract_inputs`` was not called first for a requested
            group.

        Examples
        --------
        ::

            db.extract_inputs(id_groups=(3,), subset='mach_07')
            db.extract_outputs(stage=0, id_groups=(3,), subset='mach_07')
        """
        df_cases = self.metadata.get("df_cases", pd.DataFrame())
        cases_idx = self._resolve_cases_idx(cases_idx, subset)
        sim_keys  = df_cases.loc[cases_idx, "folder"].tolist()

        for group_id in id_groups:
            ids_to_combine, key_suffix = self._parse_group_id(group_id)
            key = f"CADGroup_{key_suffix}"

            if key not in self.data_dict or \
                    'idx_sort' not in self.data_dict[key]:
                raise RuntimeError(
                    f"No idx_sort found for {key}. "
                    "Run extract_inputs first."
                )

            idx_sort_all = self.data_dict[key]['idx_sort']
            if stage >= idx_sort_all.shape[0]:
                raise ValueError(
                    f"Stage {stage} is out of bounds for idx_sort."
                )

            mesh0     = self.load_vtu_from_stage(sim_keys[0], stage, vtu_type)
            var_names = [
                v for v in mesh0.cell_data.keys()
                if var_name_excluded is None or v not in var_name_excluded
            ]
            var_storage    = {v: [] for v in var_names}
            expected_ncells = None

            for cont, case_i in enumerate(cases_idx):
                sim_key = sim_keys[cont]
                if verbose:
                    print(
                        f'\t cont={cont}  case={case_i}  folder={sim_key}'
                    )

                mesh   = self.load_vtu_from_stage(sim_key, stage, vtu_type)
                mask   = np.isin(mesh.cell_data["CADGroupID"], ids_to_combine)
                ncells = np.sum(mask)

                if expected_ncells is None:
                    expected_ncells = ncells
                elif ncells != expected_ncells:
                    raise ValueError(
                        f"Inconsistent cell count for {key} in '{sim_key}': "
                        f"{ncells} vs {expected_ncells}."
                    )

                sorter = idx_sort_all[stage, cont].astype(np.int32)
                for var_name in var_names:
                    data_masked = np.array(mesh.cell_data[var_name])[mask]
                    if data_masked.ndim == 1:
                        var_storage[var_name].append(data_masked[sorter])
                    elif data_masked.ndim == 2:
                        var_storage[var_name].append(data_masked[sorter, :])
                    else:
                        raise ValueError(
                            f"Variable '{var_name}' has unsupported "
                            f"ndim {data_masked.ndim}."
                        )

            self.data_dict.setdefault(key, {})
            self.data_dict[key].setdefault('Vars', {})
            self.data_dict[key]['Vars'].setdefault(str(stage), {})

            for var_name in var_names:
                arr = np.stack(var_storage[var_name], axis=0)
                if arr.ndim == 2:
                    self.data_dict[key]['Vars'][str(stage)][var_name] = (
                        arr.T.astype(np.float64)
                    )
                elif arr.ndim == 3:
                    self.data_dict[key]['Vars'][str(stage)][var_name] = (
                        np.transpose(arr, (2, 1, 0)).astype(np.float64)
                    )
                else:
                    raise RuntimeError("Unexpected stacked array dimension.")

    # ── Mesh utilities ────────────────────────────────────────────────────────

    def load_vtu_from_stage(
        self,
        case_name: str,
        stage: int,
        vtu_type: Literal["surface", "volume"] = "surface",
        verbose: bool = False,
    ) -> pv.UnstructuredGrid:
        """
        Load a .vtu file for a given simulation and stage.

        Parameters
        ----------
        case_name : str
            Key in self.sim_metadata (folder name).
        stage : int
            Stage number to load.
        vtu_type : str
            'surface' or 'volume'. Default 'surface'.
        verbose : bool
            Print mesh details if True.

        Returns
        -------
        pyvista.UnstructuredGrid

        Raises
        ------
        FileNotFoundError
            If no matching .vtu file is found.
        """
        sim   = self.sim_metadata[case_name]
        files = sim["stages"].get(stage, {}).get("files", [])
        path  = sim["path"]

        for fname in files:
            if fname.endswith(".vtu") and vtu_type in fname:
                mesh = pv.read(os.path.join(path, fname))
                mesh = SAM.Backpack.ensure_cell_data(mesh)
                if verbose:
                    print(f"Mesh from '{sim['folder']}' loaded")
                    print(f"  Points: {mesh.n_points}")
                    for k in mesh.cells_dict:
                        print(f"  {k}: {mesh.cells_dict[k].shape}")
                return mesh

        raise FileNotFoundError(
            f"No .vtu file with type '{vtu_type}' found in "
            f"stage {stage} of simulation '{sim['folder']}'."
        )

    def print_available_cadgroup_ids(
        self,
        stage: int,
        vtu_type: Literal["surface", "volume"] = "surface",
    ) -> None:
        """
        Print available CADGroupID and cell_data key combinations across
        all simulations.

        Parameters
        ----------
        stage : int
            Stage number to inspect.
        vtu_type : str
            Type of .vtu file. Default 'surface'.
        """
        summary: dict = defaultdict(list)
        for sim_key, sim in self.sim_metadata.items():
            try:
                mesh     = self.load_vtu_from_stage(sim_key, stage, vtu_type)
                cad_ids  = tuple(sorted(np.unique(mesh.cell_data["CADGroupID"])))
                cell_keys = tuple(sorted(mesh.cell_data.keys()))
                summary[(cad_ids, cell_keys)].append(sim["folder"])
            except Exception as exc:
                print(f"Error in simulation '{sim_key}': {exc}")

        print("\nCADGroupID / cell_data summary:")
        for (cad_ids, cell_keys), folders in summary.items():
            print(f"  CADGroupIDs : {cad_ids}")
            print(f"  cell_data   : {cell_keys}")
            print(f"  Simulations : {folders}\n")

    # ── Lookup helpers ────────────────────────────────────────────────────────

    def case_per_idx(self, idx: int) -> str:
        """
        Return the sim_metadata folder name for a df_state row index.

        Tries ``df_cases['folder']`` first; falls back to matching design
        variable values by proximity.

        Parameters
        ----------
        idx : int
            Row index in df_state / df_cases.

        Returns
        -------
        str : folder name in sim_metadata.
        """
        df_cases = self.metadata.get('df_cases', None)
        if df_cases is not None and 'folder' in df_cases.columns:
            if 'case_idx' in df_cases.columns:
                match = df_cases.loc[df_cases['case_idx'] == idx, 'folder']
                if not match.empty and pd.notna(match.iloc[0]):
                    return match.iloc[0]
            try:
                folder = df_cases.at[idx, 'folder']
                if pd.notna(folder):
                    return folder
            except Exception:
                pass

        row = self.df_state.loc[idx]
        for case_name, sim in self.sim_metadata.items():
            try:
                if all(
                    np.isclose(float(sim[var]), float(row[var]))
                    for var in self.metadata['design_vars']
                ):
                    return case_name
            except Exception:
                continue

        raise KeyError(
            f"No case found in sim_metadata for df_state idx={idx}."
        )

    # ── Visualisation ─────────────────────────────────────────────────────────

    def plot_state(self, figsize: tuple = (10, 8)) -> None:
        """
        Plot the design-variable space coloured by simulation completion state.

        Draws a single scatter plot of the varying design variables (1, 2 or
        3 of them), colouring each point by ``df_state['stage']`` — the
        number of solver stages completed for that case, ranging from
        ``0`` (not started) to ``self.metadata['num_stages']`` (finished).

        A discrete colormap with ``num_stages + 1`` categories is used (one
        per possible completion state: not started, one or more
        intermediate "in progress" states, and finished), so that every
        completion level gets its own distinct colour instead of collapsing
        the last "in progress" state and the "finished" state into the same
        bin.

        Parameters
        ----------
        figsize : tuple
            Figure size. Default (10, 8).

        Raises
        ------
        ValueError
            If fewer than one design variable actually varies across cases,
            or if more than three design variables vary (only 1-D, 2-D and
            3-D visualisations are supported).

        Examples
        --------
        ::

            db = FRODO(root_dir='/data/sim', format='CODA')
            db.plot_state()
        """
        num_stages  = self.metadata['num_stages']
        design_vars = self.metadata['design_vars']
        df_state    = self.df_state

        # ── Discrete colormap: one bin per possible stage value (0..num_stages) ──
        num_categories = num_stages + 1
        cmap_custom = plt.get_cmap("RdYlGn", num_categories)
        norm        = BoundaryNorm(
            np.arange(-0.5, num_categories + 0.5, 1), cmap_custom.N
        )

        dvf = [v for v in design_vars if df_state[v].nunique() > 1]

        if len(dvf) < 1:
            raise ValueError(
                "At least one varying design variable is required."
            )
        if len(dvf) > 3:
            raise ValueError(
                "plot_state only supports 1, 2 or 3 varying design "
                f"variables (found {len(dvf)}: {dvf})."
            )

        legend_handles = [
            plt.Line2D([0], [0], marker='o', color='w', label='Not started',
                    markerfacecolor='red',    markersize=10),
            plt.Line2D([0], [0], marker='o', color='w', label='In progress',
                    markerfacecolor='yellow', markersize=10),
            plt.Line2D([0], [0], marker='o', color='w', label='Finished',
                    markerfacecolor='green',  markersize=10),
        ]
        mask_fin = (
            df_state['stage'].values == np.max(df_state['stage'].values)
        )
        pct = mask_fin.sum() / len(mask_fin) * 100
        title=f"Status of cases - Finished cases {pct:.2f}%"
        if len(dvf) == 1:
            fig, ax = plt.subplots(1, 1, figsize=figsize)
            y_dummy = np.zeros(len(df_state))
            sc = ax.scatter(
                df_state[dvf[0]], y_dummy,
                c=df_state['stage'], cmap=cmap_custom, norm=norm, s=100,
            )
            ax.set_yticks([])
            ax.set(xlabel=dvf[0], title=title)
            ax.grid(axis='x')
            for i, x in enumerate(df_state[dvf[0]].values):
                offset = (0, 10) if df_state['stage'][i] != 0 else (0, -12)
                ax.annotate(
                    f"{i}", (x, 0), textcoords="offset points",
                    xytext=offset, ha='center', fontsize=8,
                )
            ax.legend(handles=legend_handles, loc='lower center',
                    bbox_to_anchor=(1.15, 0.5), ncols=1)
            fig.colorbar(sc, ax=ax, label="Completed stages")

        elif len(dvf) == 2:
            fig, ax = plt.subplots(1, 1, figsize=figsize)
            sc = ax.scatter(
                df_state[dvf[0]], df_state[dvf[1]],
                c=df_state['stage'], cmap=cmap_custom, norm=norm, s=100,
            )
            ax.set(xlabel=dvf[0], ylabel=dvf[1], title=title)
            ax.grid()
            for i, (x, y) in enumerate(
                zip(df_state[dvf[0]].values, df_state[dvf[1]].values)
            ):
                offset = (0, 10) if df_state['stage'][i] != 0 else (0, -12)
                ax.annotate(
                    f"{i}", (x, y), textcoords="offset points",
                    xytext=offset, ha='center', fontsize=8,
                )
            ax.legend(handles=legend_handles, loc='lower center',
                    bbox_to_anchor=(1.15, 0.5), ncols=1)
            # fig.colorbar(sc, ax=ax, label="Completed stages")

        elif len(dvf) == 3:
            fig = plt.figure(figsize=figsize)
            ax  = fig.add_subplot(111, projection='3d')
            sc = ax.scatter(
                df_state[dvf[0]], df_state[dvf[1]], df_state[dvf[2]],
                c=df_state['stage'], cmap=cmap_custom, norm=norm, s=100,
            )
            ax.set(xlabel=dvf[0], ylabel=dvf[1], zlabel=dvf[2],
                title=title)
            ax.grid()
            ax.legend(handles=legend_handles, loc='lower center',
                    bbox_to_anchor=(1.15, 0.5), ncols=1)
            fig.colorbar(sc, ax=ax, label="Completed stages", shrink=0.6)

        fig.tight_layout()
        fig.show()

    def plot_integrals_from_case(
        self,
        case_name: str = None,
        case_idx: Union[int, None] = None,
        stage: Union[list, tuple, str] = 'all',
        save_dir: Union[str, None] = None,
        **kwargs,
    ) -> None:
        """
        Plot wall boundary integral variables for a single simulation.

        Parameters
        ----------
        case_name : str or None
            Folder name in sim_metadata.
        case_idx : int or None
            df_state index (used when case_name is None).
        stage : list, tuple or 'all'
            Stages to include.
        save_dir : str or None
            If given, saves the figure here instead of displaying it.
        """
        if case_name is None:
            if case_idx is None:
                raise ValueError("Provide either case_name or case_idx.")
            case_name = self.case_per_idx(case_idx)

        case_path = self.sim_metadata[case_name]['path']
        stages    = (
            list(self.sim_metadata[case_name]['stages'].keys())
            if stage == 'all' else stage
        )

        files = SAM.Backpack.pattern_pocket.find_files(
            case_path, file_end = "_wall_boundary_integrals.dat"
        )
        if not files:
            raise ValueError(
                f"No '_wall_boundary_integrals.dat' files found in "
                f"{case_path}."
            )
        if stages is not None:
            files = [
                f for f in files
                if any(f"_{s}_" in f for s in stages)
            ]
            if not files:
                raise ValueError(
                    f"No files found for stages {stages} in {case_path}."
                )

        df = SAM.Backpack.get_df_from_csv(files)
        if "Iteration" not in df.columns:
            raise ValueError(
                "Column 'Iteration' not found; cannot detect stages."
            )
        df["stage"] = df["Iteration"].diff().lt(0).cumsum()

        titles = df.columns
        colors = plt.get_cmap("viridis")(np.linspace(0, 1, 3))
        fig, ax = plt.subplots(1, 1, figsize=kwargs.get('figsize', (10, 8)))

        for color, cy in zip(colors, [1, 2, 3]):
            ax.plot(df[titles[0]], df[titles[cy]],
                    color=color, label=f"{titles[cy]}")

        for idx in df.index[df["stage"].diff().fillna(0) != 0]:
            ax.axvline(
                x=df.iloc[idx, 0], color="black",
                linestyle="--", linewidth=1, alpha=0.5,
            )

        ax.set_ylabel("Values")
        ax.legend()
        ax.grid(True)
        title = (
            f"Wall Integrals – {case_name}"
            if case_idx is None
            else f"Wall Integrals – Case {case_idx}"
        )
        fig.suptitle(title, fontsize=16)

        if save_dir is not None:
            os.makedirs(save_dir, exist_ok=True)
            save_path = os.path.join(
                save_dir,
                f"{case_name}_stages_{'_'.join(map(str, stages))}"
                "_wall_integrals.png",
            )
            fig.savefig(save_path, bbox_inches='tight')
            print(f"Figure saved to {save_path}")
        else:
            plt.show()

    # ── Private helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _parse_group_id(group_id) -> tuple:
        """Return (ids_to_combine, key_suffix) from a group_id."""
        if isinstance(group_id, tuple):
            return group_id, "_".join(map(str, group_id))
        elif isinstance(group_id, int):
            return (group_id,), str(group_id)
        else:
            raise TypeError(
                f"id_groups elements must be int or tuple, "
                f"got {type(group_id)}."
            )