"""
readers/coda.py
===============
Reader for CODA CFD solver output.

Expected directory layout
--------------------------
::

    root_dir/
    ├── metadata/
    │   └── cases_metadata.json          ← generated by GANDALF
    └── outputs/
        ├── aoa_3.00_mach_0.750/
        │   ├── output_0_surface.vtu
        │   ├── output_0__monitors_*.dat
        │   └── ...
        └── aoa_5.00_mach_0.750/
            └── ...

If ``cases_metadata.json`` is missing, the reader attempts to infer the
folder format automatically from the folder names in ``outputs/``.
"""

import os
import re
import json
import warnings
import time
from collections import defaultdict
from typing import Literal, Union

import numpy as np
import pandas as pd
import pyvista as pv
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.colors import BoundaryNorm

from ..sam import SAM
from .base import BaseReader


class CODAReader(BaseReader):
    """
    Reader for CODA CFD solver output (.vtu surface / volume files).

    Parameters
    ----------
    root_dir : str
        Path to the dataset root directory (passed by FRODO).

    Attributes set after ``parse_simulation_dirs``
    -----------------------------------------------
    metadata : dict
        Keys: 'eq_type', 'folder_fmt', 'design_vars', 'num_stages',
        'df_cases'.
    sim_metadata : dict
        Keyed by folder name.  Each value contains path, stage dict and
        design-variable values.
    df_state : pd.DataFrame
        One row per simulation. Columns: design vars + 'stage' + 'folder'.
    """

    def __init__(self, root_dir: str, **kwargs):
        super().__init__(root_dir, **kwargs)
        self.output_dir = os.path.join(self.root_dir, "outputs")
        print(f'\n NEW CODA SIMULATION WILL BE LOADED FROM {root_dir}')

        try:
            meta_path = os.path.join(root_dir, 'metadata', 'cases_metadata.json')
            with open(meta_path, 'r') as fh:
                cm = json.load(fh)

            self.metadata = {
                'eq_type':     cm.get('eq_type',    None),
                'folder_fmt':  cm.get('folder_fmt', None),
                'design_vars': cm.get('design_vars', None),
                'num_stages':  cm.get('num_stages', None),
            }

            df_cases = (
                pd.DataFrame.from_dict(cm.get('df_cases', {}))
                .sort_values(by=self.metadata['design_vars'][0],
                             ignore_index=True, axis=0)
                .reset_index(drop=True)
            )
            if "case_idx" not in df_cases.columns:
                df_cases.insert(0, "case_idx", df_cases.index.astype(np.int32))
            self.metadata['df_cases'] = df_cases

        except Exception as exc:
            print(
                "WARNING: cases_metadata.json not found or could not be "
                "loaded. Folder format will be inferred from folder names.\n"
            )
            print(exc)
            self._infer_metadata_from_folders()

    # ── Metadata inference fallback ───────────────────────────────────────────

    def _infer_metadata_from_folders(self):
        """Infer metadata from output folder names when JSON is missing."""
        folders       = os.listdir(self.output_dir)
        possible_sep  = ['_', '-']
        sep_list, params_list, nfiles_list = [], [], []

        for folder in folders:
            for sep in possible_sep:
                if sep in folder:
                    parts = folder.split(sep)
                    params = [
                        float(re.findall(r"-?\d+\.?\d*", p)[0])
                        for p in parts
                        if re.findall(r"-?\d+\.?\d*", p)
                    ]
                    params_list.append(params)
                    sep_list.append(sep)
                    nfiles_list.append(len(
                        SAM.Backpack.pattern_pocket.find_files(
                            os.path.join(self.output_dir, folder),
                            file_end='.h5', not_contains='ci',
                        )
                    ))

        if not params_list:
            raise ValueError(
                "No simulation folders found or no numeric parameters "
                "detected in folder names."
            )

        if not (
            all(len(p) == len(params_list[0]) for p in params_list)
            and all(s == sep_list[0] for s in sep_list)
            and all(n == nfiles_list[0] for n in nfiles_list)
        ):
            raise ValueError(
                "Inconsistent folder naming. "
                "Please provide a valid cases_metadata.json file."
            )

        parts = folders[0].split(sep_list[0])
        self.metadata = {
            'eq_type': None,
            'folder_fmt': sep_list[0].join([
                p if not re.findall(r"-?\d+\.?\d*", p) else "{}"
                for p in parts
            ]),
            'design_vars': [parts[i] for i in range(0, len(parts), 2)],
            'num_stages':  nfiles_list[0],
        }

        df_arr = np.zeros((len(folders), len(params_list[0])), dtype=float)
        for f_idx, folder in enumerate(folders):
            df_arr[f_idx, :] = params_list[f_idx]

        df_cases = pd.DataFrame(
            df_arr, columns=self.metadata['design_vars']
        ).reset_index(drop=True)
        df_cases.insert(0, "case_idx", df_cases.index.astype(np.int32))
        self.metadata['df_cases'] = df_cases

    # ── BaseReader interface ──────────────────────────────────────────────────

    def parse_simulation_dirs(self) -> None:
        """
        Walk ``outputs/`` and build ``sim_metadata`` and ``df_state``.

        Matches folder names against the format pattern, maps each folder
        to the closest entry in ``df_cases`` (by Euclidean distance in the
        design-variable space), and counts available stages.

        Populates
        ---------
        self.sim_metadata : dict
            Keyed by folder name. Values: path, stages dict, design-var
            values, computation_times list.
        self.df_state : pd.DataFrame
            One row per matched simulation.
        """
        pattern = SAM.Backpack.pattern_pocket.FilenamePattern.from_template(
            self.metadata["folder_fmt"], numeric=True
        ).compiled

        for folder in os.listdir(self.output_dir):
            if not pattern.match(folder):
                continue

            nums_folder = np.array(
                [float(x) for x in re.compile(r"[-\d\.]+").findall(folder)],
                dtype=float,
            )
            nums_df = self.metadata['df_cases'][
                self.metadata['design_vars']
            ].values
            idx_closest = np.argmin(
                np.linalg.norm(nums_df - nums_folder, axis=1)
            )
            nums = (
                self.metadata['df_cases']
                .iloc[idx_closest][self.metadata['design_vars']]
                .values.tolist()
            )
            self.metadata['df_cases'].at[idx_closest, 'folder'] = folder

            full_path = os.path.join(self.output_dir, folder)
            if not os.path.isdir(full_path):
                continue

            stage_dict: dict = {}
            for fname in os.listdir(full_path):
                if fname.startswith("output_"):
                    parts = fname.split("_")
                    if len(parts) >= 2:
                        stage_raw = os.path.splitext(parts[1])[0]
                        if stage_raw.isdigit():
                            stage = int(stage_raw)
                            ext   = os.path.splitext(fname)[-1].lstrip(".")
                            stage_dict.setdefault(
                                stage, {"files": [], "types": set()}
                            )
                            stage_dict[stage]["files"].append(fname)
                            stage_dict[stage]["types"].add(ext)

            for stage in stage_dict:
                stage_dict[stage]["types"] = list(stage_dict[stage]["types"])

            self.sim_metadata[folder] = {
                "folder":            folder,
                "path":              full_path,
                "stages":            stage_dict,
                "computation times": [],
            }
            self.sim_metadata[folder].update(
                {var: val for var, val in
                 zip(self.metadata["design_vars"], nums)}
            )

        print(f"{len(self.sim_metadata)} simulations found.")

        n_dv = len(self.metadata['design_vars'])
        state_array = np.zeros(
            (len(self.sim_metadata), n_dv + 1), dtype=float
        )
        for n_sim, sim_key in enumerate(self.sim_metadata):
            sim = self.sim_metadata[sim_key]
            for i, var in enumerate(self.metadata['design_vars']):
                state_array[n_sim, i] = sim[var]
            state_array[n_sim, -1] = len(sim["stages"])

        df_state = (
            pd.DataFrame(
                state_array,
                columns=self.metadata['design_vars'] + ['stage'],
            )
            .sort_values(by=self.metadata['design_vars'][0])
            .reset_index(drop=True)
        )
        self.df_state = pd.merge(
            df_state, self.metadata['df_cases'],
            on=self.metadata['design_vars'], how='left',
        )

    def extract_inputs(
        self,
        id_groups: Union[int, tuple],
        vtu_type: Literal['volume', 'surface'] = 'surface',
        method_to_sort: Literal[
            'lexsort', 'centroid', 'kdtree', 'convex_hull'
        ] = 'lexsort',
        cases_idx: Union[list, tuple, int, str] = 'all',
        verbose: bool = False,
    ) -> None:
        """
        Extract input mesh and metadata for one or multiple CADGroup IDs.

        Parameters
        ----------
        id_groups : int or tuple
            Group IDs to process. A tuple of ints merges those groups into
            a single CADGroup key.
            Examples: ``(3,)`` for group 3 alone;
            ``((1, 2), 3)`` to merge groups 1+2 and also process group 3.
        vtu_type : str
            Type of .vtu file to load. Default 'surface'.
        method_to_sort : str
            Cell-centroid sorting method.
            Options: 'lexsort', 'centroid', 'kdtree', 'convex_hull'.
        cases_idx : list, tuple, int or 'all'
            Subset of cases (by df_cases row index) to process. Default 'all'.
        verbose : bool
            Print per-case progress.

        Populates
        ---------
        self.data_dict[key] with:
        'Coord', 'NodeCoord', 'FlCc', 'Conec',
        'idx_sort', 'idx_sort_nodes', 'eltype', 'cellOrder', 'pointOrder'.
        """
        num_stages  = self.metadata.get("num_stages", 1)
        design_vars = self.metadata.get("design_vars", [])
        df_cases    = self.metadata.get("df_cases", pd.DataFrame())

        cases_idx = self._normalise_cases_idx(cases_idx, df_cases)
        sim_keys  = df_cases.loc[cases_idx, "folder"].tolist()
        ncases    = len(sim_keys)

        sort_fn_map = {
            'lexsort':     SAM.Weapons.sort_lexsort,
            None:          SAM.Weapons.sort_lexsort,
            'centroid':    SAM.Weapons.sort_by_centroid,
            'kdtree':      SAM.Weapons.sort_closed_curve_by_kdtree,
            'convex_hull': SAM.Weapons.sort_points_by_hull_projection,
        }
        if method_to_sort not in sort_fn_map:
            raise ValueError(
                f"method_to_sort '{method_to_sort}' not supported. "
                f"Options: {list(sort_fn_map)}."
            )
        sort_fn = sort_fn_map[method_to_sort]

        for group_id in id_groups:
            ids_to_combine, key_suffix = self._parse_group_id(group_id)
            key = f"CADGroup_{key_suffix}"

            Coord_base = NodeCoord_base = None
            Conec_base = eltype_base = cellOrder_base = pointOrder_base = None
            FlCc = idx_sort = idx_sort_nodes = None

            for stage in range(num_stages):
                if verbose:
                    print(f'Stage {stage}:')
                for cont, case_i in enumerate(cases_idx):
                    sim_key = sim_keys[cont]
                    if verbose:
                        print(f'\t cont={cont}  case={case_i}  folder={sim_key}')
                    try:
                        mesh = self.load_vtu_from_stage(sim_key, stage, vtu_type)

                        if "CADGroupID" not in mesh.cell_data:
                            raise ValueError(
                                "'CADGroupID' not found in mesh cell_data."
                            )

                        mask      = np.isin(mesh.cell_data["CADGroupID"],
                                            ids_to_combine)
                        celdas    = mesh.extract_cells(mask)
                        centroids = np.array(
                            celdas.cell_centers().points, dtype=np.float64
                        )
                        nodes        = np.array(celdas.points, dtype=np.float64)
                        connectivity = (
                            SAM.Backpack.get_unified_connectivity(mesh)[mask]
                        )

                        centroids_sorted, idx       = sort_fn(points=centroids)
                        nodes_sorted,     idx_nodes = sort_fn(points=nodes)

                        if stage == 0 and cont == 0:
                            npoints = centroids.shape[0]
                            nnodes  = nodes.shape[0]

                            idx_sort = np.zeros(
                                (num_stages, ncases, npoints), dtype=np.int32
                            )
                            idx_sort_nodes = np.zeros(
                                (num_stages, ncases, nnodes), dtype=np.int32
                            )
                            FlCc          = np.zeros(
                                (ncases, len(design_vars)), dtype=np.float64
                            )
                            Coord_base     = centroids_sorted.copy()
                            NodeCoord_base = nodes_sorted.copy()
                            Conec_base     = connectivity.copy()
                            eltype_base    = celdas.celltypes.copy()
                            cellOrder_base = np.arange(
                                celdas.n_cells, dtype=np.float64
                            )
                            pointOrder_base = np.arange(
                                celdas.n_points, dtype=np.float64
                            )
                        else:
                            for base, current, label in [
                                (Coord_base,     centroids_sorted, "cell"),
                                (NodeCoord_base, nodes_sorted,     "node"),
                            ]:
                                if not SAM.Backpack.same_columns(
                                    np.stack([base, current], axis=0)
                                ):
                                    raise ValueError(
                                        f"Inconsistent {label} coordinates "
                                        f"at stage {stage}, case {sim_key}."
                                    )

                        idx_sort[stage, cont]       = idx
                        idx_sort_nodes[stage, cont] = idx_nodes
                        if stage == 0:
                            FlCc[cont] = [
                                self.sim_metadata[sim_key][p]
                                for p in design_vars
                            ]

                    except Exception as exc:
                        print(
                            f"Error reading inputs for '{sim_key}', "
                            f"group {group_id}, stage {stage}: {exc}"
                        )

            self.data_dict.setdefault(key, {}).update({
                'Coord':          Coord_base,
                'NodeCoord':      NodeCoord_base,
                'FlCc':           FlCc,
                'Conec':          Conec_base,
                'idx_sort':       idx_sort,
                'idx_sort_nodes': idx_sort_nodes,
                'eltype':         eltype_base,
                'cellOrder':      cellOrder_base,
                'pointOrder':     pointOrder_base,
            })

    def extract_outputs(
        self,
        stage: int,
        id_groups: Union[int, tuple],
        vtu_type: Literal['volume', 'surface'] = 'surface',
        cases_idx: Union[list, tuple, int, str] = 'all',
        var_name_excluded: Union[list, tuple, None] = None,
        verbose: bool = False,
    ) -> None:
        """
        Extract cell-based output variables for one or multiple CADGroup IDs.

        Requires ``extract_inputs`` to have been called first (uses
        ``idx_sort`` stored by that method).

        Parameters
        ----------
        stage : int
            Stage number to extract variables from.
        id_groups : int or tuple
            Same format as in ``extract_inputs``.
        vtu_type : str
            Type of .vtu file. Default 'surface'.
        cases_idx : list, tuple, int or 'all'
            Subset of cases. Default 'all'.
        var_name_excluded : list, tuple or None
            Variable names to skip during extraction.
        verbose : bool
            Print per-case progress.

        Populates
        ---------
        self.data_dict[key]['Vars'][str(stage)] with arrays of shape
        (n_points, n_cases) for each scalar variable.
        """
        df_cases = self.metadata.get("df_cases", pd.DataFrame())
        cases_idx = self._normalise_cases_idx(cases_idx, df_cases)
        sim_keys  = df_cases.loc[cases_idx, "folder"].tolist()

        for group_id in id_groups:
            ids_to_combine, key_suffix = self._parse_group_id(group_id)
            key = f"CADGroup_{key_suffix}"

            if key not in self.data_dict or \
                    'idx_sort' not in self.data_dict[key]:
                raise RuntimeError(
                    f"No idx_sort found for {key}. "
                    "Run extract_inputs first."
                )

            idx_sort_all = self.data_dict[key]['idx_sort']
            if stage >= idx_sort_all.shape[0]:
                raise ValueError(
                    f"Stage {stage} is out of bounds for idx_sort."
                )

            mesh0     = self.load_vtu_from_stage(sim_keys[0], stage, vtu_type)
            var_names = [
                v for v in mesh0.cell_data.keys()
                if var_name_excluded is None or v not in var_name_excluded
            ]
            var_storage    = {v: [] for v in var_names}
            expected_ncells = None

            for cont, case_i in enumerate(cases_idx):
                sim_key = sim_keys[cont]
                if verbose:
                    print(
                        f'\t cont={cont}  case={case_i}  folder={sim_key}'
                    )

                mesh   = self.load_vtu_from_stage(sim_key, stage, vtu_type)
                mask   = np.isin(mesh.cell_data["CADGroupID"], ids_to_combine)
                ncells = np.sum(mask)

                if expected_ncells is None:
                    expected_ncells = ncells
                elif ncells != expected_ncells:
                    raise ValueError(
                        f"Inconsistent cell count for {key} in '{sim_key}': "
                        f"{ncells} vs {expected_ncells}."
                    )

                sorter = idx_sort_all[stage, cont].astype(np.int32)
                for var_name in var_names:
                    data_masked = np.array(mesh.cell_data[var_name])[mask]
                    if data_masked.ndim == 1:
                        var_storage[var_name].append(data_masked[sorter])
                    elif data_masked.ndim == 2:
                        var_storage[var_name].append(data_masked[sorter, :])
                    else:
                        raise ValueError(
                            f"Variable '{var_name}' has unsupported "
                            f"ndim {data_masked.ndim}."
                        )

            self.data_dict.setdefault(key, {})
            self.data_dict[key].setdefault('Vars', {})
            self.data_dict[key]['Vars'].setdefault(str(stage), {})

            for var_name in var_names:
                arr = np.stack(var_storage[var_name], axis=0)
                if arr.ndim == 2:
                    self.data_dict[key]['Vars'][str(stage)][var_name] = (
                        arr.T.astype(np.float64)
                    )
                elif arr.ndim == 3:
                    self.data_dict[key]['Vars'][str(stage)][var_name] = (
                        np.transpose(arr, (2, 1, 0)).astype(np.float64)
                    )
                else:
                    raise RuntimeError("Unexpected stacked array dimension.")

    # ── Mesh utilities ────────────────────────────────────────────────────────

    def load_vtu_from_stage(
        self,
        case_name: str,
        stage: int,
        vtu_type: Literal["surface", "volume"] = "surface",
        verbose: bool = False,
    ) -> pv.UnstructuredGrid:
        """
        Load a .vtu file for a given simulation and stage.

        Parameters
        ----------
        case_name : str
            Key in self.sim_metadata (folder name).
        stage : int
            Stage number to load.
        vtu_type : str
            'surface' or 'volume'. Default 'surface'.
        verbose : bool
            Print mesh details if True.

        Returns
        -------
        pyvista.UnstructuredGrid

        Raises
        ------
        FileNotFoundError
            If no matching .vtu file is found.
        """
        sim   = self.sim_metadata[case_name]
        files = sim["stages"].get(stage, {}).get("files", [])
        path  = sim["path"]

        for fname in files:
            if fname.endswith(".vtu") and vtu_type in fname:
                mesh = pv.read(os.path.join(path, fname))
                mesh = SAM.Backpack.ensure_cell_data(mesh)
                if verbose:
                    print(f"Mesh from '{sim['folder']}' loaded")
                    print(f"  Points: {mesh.n_points}")
                    for k in mesh.cells_dict:
                        print(f"  {k}: {mesh.cells_dict[k].shape}")
                return mesh

        raise FileNotFoundError(
            f"No .vtu file with type '{vtu_type}' found in "
            f"stage {stage} of simulation '{sim['folder']}'."
        )

    def print_available_cadgroup_ids(
        self,
        stage: int,
        vtu_type: Literal["surface", "volume"] = "surface",
    ) -> None:
        """
        Print available CADGroupID and cell_data key combinations across
        all simulations.

        Parameters
        ----------
        stage : int
            Stage number to inspect.
        vtu_type : str
            Type of .vtu file. Default 'surface'.
        """
        summary: dict = defaultdict(list)
        for sim_key, sim in self.sim_metadata.items():
            try:
                mesh     = self.load_vtu_from_stage(sim_key, stage, vtu_type)
                cad_ids  = tuple(sorted(np.unique(mesh.cell_data["CADGroupID"])))
                cell_keys = tuple(sorted(mesh.cell_data.keys()))
                summary[(cad_ids, cell_keys)].append(sim["folder"])
            except Exception as exc:
                print(f"Error in simulation '{sim_key}': {exc}")

        print("\nCADGroupID / cell_data summary:")
        for (cad_ids, cell_keys), folders in summary.items():
            print(f"  CADGroupIDs : {cad_ids}")
            print(f"  cell_data   : {cell_keys}")
            print(f"  Simulations : {folders}\n")

    # ── Lookup helpers ────────────────────────────────────────────────────────

    def case_per_idx(self, idx: int) -> str:
        """
        Return the sim_metadata folder name for a df_state row index.

        Tries ``df_cases['folder']`` first; falls back to matching design
        variable values by proximity.

        Parameters
        ----------
        idx : int
            Row index in df_state / df_cases.

        Returns
        -------
        str : folder name in sim_metadata.
        """
        df_cases = self.metadata.get('df_cases', None)
        if df_cases is not None and 'folder' in df_cases.columns:
            if 'case_idx' in df_cases.columns:
                match = df_cases.loc[df_cases['case_idx'] == idx, 'folder']
                if not match.empty and pd.notna(match.iloc[0]):
                    return match.iloc[0]
            try:
                folder = df_cases.at[idx, 'folder']
                if pd.notna(folder):
                    return folder
            except Exception:
                pass

        row = self.df_state.loc[idx]
        for case_name, sim in self.sim_metadata.items():
            try:
                if all(
                    np.isclose(float(sim[var]), float(row[var]))
                    for var in self.metadata['design_vars']
                ):
                    return case_name
            except Exception:
                continue

        raise KeyError(
            f"No case found in sim_metadata for df_state idx={idx}."
        )

    # ── Visualisation ─────────────────────────────────────────────────────────

    def plot_state(self, figsize: tuple = (15, 7)) -> None:
        """
        Plot the design-variable space coloured by simulation completion state.

        Parameters
        ----------
        figsize : tuple
            Figure size. Default (15, 7).
        """
        num_states  = self.metadata['num_stages']
        design_vars = self.metadata['design_vars']
        df_state    = self.df_state

        cmap_custom = plt.get_cmap("RdYlGn", num_states)
        norm        = BoundaryNorm(
            np.arange(-0.5, num_states + 0.5, 1), cmap_custom.N
        )
        dvf = [v for v in design_vars if df_state[v].nunique() > 1]

        if len(dvf) < 2:
            raise ValueError(
                "At least two varying design variables are required."
            )

        legend_handles = [
            plt.Line2D([0], [0], marker='o', color='w', label='Not started',
                       markerfacecolor='red',    markersize=10),
            plt.Line2D([0], [0], marker='o', color='w', label='In progress',
                       markerfacecolor='yellow', markersize=10),
            plt.Line2D([0], [0], marker='o', color='w', label='Finished',
                       markerfacecolor='green',  markersize=10),
        ]

        if len(dvf) == 2:
            fig, ax = plt.subplots(1, 2, figsize=figsize, sharey=True)
            ax[0].scatter(
                df_state[dvf[0]], df_state[dvf[1]],
                c=df_state['stage'], cmap=cmap_custom, norm=norm, s=100,
            )
            ax[0].set(xlabel=dvf[0], ylabel=dvf[1], title="Status of cases")
            ax[0].grid()
            ax[0].legend(handles=legend_handles, loc='lower center',
                         bbox_to_anchor=(1.15, 0.5), ncols=1)

            for i, (x, y) in enumerate(
                zip(df_state[dvf[0]].values, df_state[dvf[1]].values)
            ):
                offset = (0, 10) if df_state['stage'][i] != 0 else (0, -12)
                ax[0].annotate(
                    f"{i}", (x, y), textcoords="offset points",
                    xytext=offset, ha='center', fontsize=8,
                )

            mask_fin = (
                df_state['stage'].values == np.max(df_state['stage'].values)
            )
            ax[1].scatter(
                df_state[dvf[0]][mask_fin], df_state[dvf[1]][mask_fin], s=100
            )
            pct = mask_fin.sum() / len(mask_fin) * 100
            ax[1].set(xlabel=dvf[0], ylabel=dvf[1],
                      title=f"Finished cases {pct:.2f}%")
            ax[1].grid()
            fig.subplots_adjust(wspace=0.3)
            fig.show()

        elif len(dvf) == 3:
            fig, ax = plt.subplots(1, 1, figsize=figsize)
            ax.scatter(
                df_state[dvf[0]], df_state[dvf[1]], df_state[dvf[2]],
                c=df_state['stage'], cmap=cmap_custom, norm=norm, s=100,
            )
            ax.set(xlabel=dvf[0], ylabel=dvf[1], zlabel=dvf[2],
                   title="Status of cases")
            ax.grid()
            ax.legend(handles=legend_handles, loc='lower center',
                      bbox_to_anchor=(1.15, 0.5), ncols=1)

    def plot_integrals_from_case(
        self,
        case_name: str = None,
        case_idx: Union[int, None] = None,
        stage: Union[list, tuple, str] = 'all',
        save_dir: Union[str, None] = None,
        **kwargs,
    ) -> None:
        """
        Plot wall boundary integral variables for a single simulation.

        Parameters
        ----------
        case_name : str or None
            Folder name in sim_metadata.
        case_idx : int or None
            df_state index (used when case_name is None).
        stage : list, tuple or 'all'
            Stages to include.
        save_dir : str or None
            If given, saves the figure here instead of displaying it.
        """
        if case_name is None:
            if case_idx is None:
                raise ValueError("Provide either case_name or case_idx.")
            case_name = self.case_per_idx(case_idx)

        case_path = self.sim_metadata[case_name]['path']
        stages    = (
            list(self.sim_metadata[case_name]['stages'].keys())
            if stage == 'all' else stage
        )

        files = SAM.Backpack.pattern_pocket.find_files(
            case_path, file_end = "_wall_boundary_integrals.dat"
        )
        if not files:
            raise ValueError(
                f"No '_wall_boundary_integrals.dat' files found in "
                f"{case_path}."
            )
        if stages is not None:
            files = [
                f for f in files
                if any(f"_{s}_" in f for s in stages)
            ]
            if not files:
                raise ValueError(
                    f"No files found for stages {stages} in {case_path}."
                )

        df = SAM.Backpack.get_df_from_csv(files)
        if "Iteration" not in df.columns:
            raise ValueError(
                "Column 'Iteration' not found; cannot detect stages."
            )
        df["stage"] = df["Iteration"].diff().lt(0).cumsum()

        titles = df.columns
        colors = plt.get_cmap("viridis")(np.linspace(0, 1, 3))
        fig, ax = plt.subplots(1, 1, figsize=kwargs.get('figsize', (10, 8)))

        for color, cy in zip(colors, [1, 2, 3]):
            ax.plot(df[titles[0]], df[titles[cy]],
                    color=color, label=f"{titles[cy]}")

        for idx in df.index[df["stage"].diff().fillna(0) != 0]:
            ax.axvline(
                x=df.iloc[idx, 0], color="black",
                linestyle="--", linewidth=1, alpha=0.5,
            )

        ax.set_ylabel("Values")
        ax.legend()
        ax.grid(True)
        title = (
            f"Wall Integrals – {case_name}"
            if case_idx is None
            else f"Wall Integrals – Case {case_idx}"
        )
        fig.suptitle(title, fontsize=16)

        if save_dir is not None:
            os.makedirs(save_dir, exist_ok=True)
            save_path = os.path.join(
                save_dir,
                f"{case_name}_stages_{'_'.join(map(str, stages))}"
                "_wall_integrals.png",
            )
            fig.savefig(save_path, bbox_inches='tight')
            print(f"Figure saved to {save_path}")
        else:
            plt.show()

    # ── Private helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _normalise_cases_idx(
        cases_idx,
        df_cases: pd.DataFrame,
    ) -> list:
        """Normalise cases_idx to a sorted list of integers."""
        if isinstance(cases_idx, str):
            if cases_idx.lower() == "all":
                cases_idx = list(range(len(df_cases)))
            else:
                raise ValueError(
                    "Invalid string for cases_idx. Use 'all'."
                )
        elif isinstance(cases_idx, int):
            cases_idx = [cases_idx]
        elif isinstance(cases_idx, range):
            cases_idx = list(cases_idx)
        elif isinstance(cases_idx, (list, tuple)):
            cases_idx = list(cases_idx)
        else:
            raise ValueError(
                "cases_idx must be 'all', int, list[int], tuple[int] or range."
            )

        if any(i >= len(df_cases) or i < 0 for i in cases_idx):
            raise IndexError("cases_idx contains out-of-range values.")

        return cases_idx

    @staticmethod
    def _parse_group_id(group_id) -> tuple:
        """Return (ids_to_combine, key_suffix) from a group_id."""
        if isinstance(group_id, tuple):
            return group_id, "_".join(map(str, group_id))
        elif isinstance(group_id, int):
            return (group_id,), str(group_id)
        else:
            raise TypeError(
                f"id_groups elements must be int or tuple, "
                f"got {type(group_id)}."
            )